version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=my-secret-pw
      - MYSQL_DB=asset_managment
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: asset_managment
    ports:
      - "3307:3306" # Cambia la porta esposta qui
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
